//! Username, password, and the percent-encoder used to embed them in URLs.
//!
//! The encoder matches Swift's `CharacterSet.urlUserAllowed` minus
//! `:@/?#[]`, so the wire output is byte-identical to the Swift app.

use std::fmt::Write as _;

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// A non-empty, whitespace-trimmed proxy username.
///
/// `Debug` and `Display` redact the contents to match [`Password`].
/// Usernames are less sensitive than passwords, but they are still
/// account identifiers — leaking them via a stray `info!("user: {u}")`
/// or panic message would aid credential stuffing. The plaintext is
/// reachable only via [`Username::as_str`], which callers must treat
/// as sensitive (do not log, do not include in errors that cross the
/// process boundary).
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct Username(String);

/// Maximum username length, mirroring the Laravel panel's
/// `TextInput::make('username')->maxLength(64)` validation rule
/// (panel/app/Filament/Resources/ProxyAccountResource.php). Keeping the
/// client and server in lock-step here means a username the panel
/// rejects with HTTP 422 also fails locally before the engine ever
/// hits the wire — the user sees the same constraint in both places.
pub const USERNAME_MAX_LEN: usize = 64;

/// Maximum password length. Mirrors the typical Laravel VARCHAR(255)
/// column cap on `password_cleartext_encrypted` (the column is wider,
/// but the cleartext that goes IN must fit; passwords longer than 255
/// chars are not generated by `App\Services\PasswordGenerator` and
/// would round-trip oddly through Crypt).
pub const PASSWORD_MAX_LEN: usize = 255;

impl Username {
    /// Parses and validates a username.
    ///
    /// **Domain-F#2 (v0.1.7.17):** rejects control characters
    /// (NUL, newlines, ANSI escapes) and the URL-userinfo
    /// metacharacters `@` and `:` that would make the percent-
    /// encoded output ambiguous downstream. Previously `parse`
    /// only checked emptiness, so `"a@b:c\n/d"` parsed as a
    /// valid username and produced a syntactically odd
    /// percent-encoding that downstream HTTP-header writers
    /// could split on.
    ///
    /// **Hardening (v2.0.18-pre):** mirrors the Laravel panel's
    /// `alphaDash` + `maxLength(64)` rules so the client and
    /// server agree on which usernames are valid. `alphaDash` =
    /// ASCII letters, digits, dash, underscore. The Rust side
    /// previously accepted any non-control, non-`@`, non-`:` char
    /// — which would still produce a usable percent-encoding but
    /// would be 422-rejected at the panel on creation. Aligning
    /// the rules means a username that passes here will also
    /// pass server-side validation, eliminating "valid client
    /// side, rejected server side" as a failure mode.
    ///
    /// # Errors
    ///
    /// - [`InvalidCredentials::EmptyUsername`] if trimmed input
    ///   is empty.
    /// - [`InvalidCredentials::UsernameTooLong`] if the trimmed
    ///   input exceeds [`USERNAME_MAX_LEN`].
    /// - [`InvalidCredentials::IllegalUsernameChar`] if the
    ///   trimmed input contains a non-`alphaDash` character.
    pub fn parse(input: &str) -> Result<Self, InvalidCredentials> {
        let trimmed = input.trim();
        if trimmed.is_empty() {
            return Err(InvalidCredentials::EmptyUsername);
        }
        if trimmed.len() > USERNAME_MAX_LEN {
            return Err(InvalidCredentials::UsernameTooLong {
                max: USERNAME_MAX_LEN,
                got: trimmed.len(),
            });
        }
        if let Some(bad) = trimmed.chars().find(|c| !is_alpha_dash(*c)) {
            return Err(InvalidCredentials::IllegalUsernameChar(bad));
        }
        Ok(Self(trimmed.to_owned()))
    }

    /// Returns the username as a string slice. Sensitive — callers
    /// must not log it or persist it unencrypted outside the audited
    /// `Credentials` -> `EncodedCredentials` -> `naive config.json`
    /// path that always lands behind 0600 file permissions.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Debug for Username {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Match Password: never reveal plaintext through Debug. A
        // panic that captures Credentials, a tracing macro that
        // formats the struct with `{:?}`, or a test snapshot would
        // otherwise expose the username.
        f.debug_tuple("Username").field(&"***").finish()
    }
}

impl std::fmt::Display for Username {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Display is intentionally redacted for the same reason as
        // Debug. URL embedding goes through `percent_encoded()` which
        // calls `as_str()` directly, so the plaintext path is the
        // explicit one — implicit `format!("{}", username)` cannot
        // accidentally leak.
        f.write_str("***")
    }
}

impl TryFrom<String> for Username {
    type Error = InvalidCredentials;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::parse(&value)
    }
}

impl From<Username> for String {
    fn from(value: Username) -> Self {
        value.0
    }
}

/// A non-empty, whitespace-trimmed proxy password.
///
/// `Debug` and `Display` redact the contents. The plaintext is reachable only
/// via [`Password::expose_secret`] — callers that invoke it must treat the
/// returned string as sensitive (do not log, do not serialize unencrypted).
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct Password(String);

impl Password {
    /// Parses and validates a password.
    ///
    /// **Hardening (v2.0.18-pre):** caps trimmed length at
    /// [`PASSWORD_MAX_LEN`] to match the server's stored-cleartext
    /// column. `App\Services\PasswordGenerator::make()` emits
    /// strings far below this cap, so any longer input is either a
    /// user-typed mistake (paste of a multi-line cert?) or a
    /// hostile fuzzed value — reject locally before naive sees it.
    ///
    /// # Errors
    ///
    /// - [`InvalidCredentials::EmptyPassword`] if the trimmed
    ///   input is empty.
    /// - [`InvalidCredentials::PasswordTooLong`] if the trimmed
    ///   input exceeds [`PASSWORD_MAX_LEN`].
    pub fn parse(input: &str) -> Result<Self, InvalidCredentials> {
        let trimmed = input.trim();
        if trimmed.is_empty() {
            return Err(InvalidCredentials::EmptyPassword);
        }
        if trimmed.len() > PASSWORD_MAX_LEN {
            return Err(InvalidCredentials::PasswordTooLong {
                max: PASSWORD_MAX_LEN,
                got: trimmed.len(),
            });
        }
        Ok(Self(trimmed.to_owned()))
    }

    /// Returns the plaintext password.
    ///
    /// The result is sensitive. Callers must not log it or persist it
    /// unencrypted. The verbose name is intentional, modelled after the
    /// `secrecy` crate's `ExposeSecret` trait.
    #[must_use]
    pub fn expose_secret(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Debug for Password {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Password").field(&"***").finish()
    }
}

impl TryFrom<String> for Password {
    type Error = InvalidCredentials;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::parse(&value)
    }
}

impl From<Password> for String {
    fn from(value: Password) -> Self {
        value.0
    }
}

/// Username and password presented to the upstream proxy.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Credentials {
    /// Account name.
    pub username: Username,
    /// Secret.
    pub password: Password,
}

impl Credentials {
    /// Constructs a credential pair from already-validated parts.
    #[must_use]
    pub const fn new(username: Username, password: Password) -> Self {
        Self { username, password }
    }

    /// Returns a percent-encoded copy of these credentials, suitable for
    /// embedding in a URL's userinfo segment.
    #[must_use]
    pub fn percent_encoded(&self) -> EncodedCredentials {
        EncodedCredentials::new(
            percent_encode_userinfo(self.username.as_str()),
            percent_encode_userinfo(self.password.expose_secret()),
        )
    }
}

/// Percent-encoded credential pair, ready for URL embedding.
///
/// Fields are private with read accessors so consumers can build
/// the `https://user:pass@host` form without ever holding the raw
/// `String`s — and so any future telemetry or debug-print can't
/// dump them by accident. `Drop` overwrites the heap bytes before
/// freeing them; for an LTSC line that documents credential
/// hygiene this is the leakiest type otherwise (the rest of the
/// pipeline already redacts).
#[derive(Clone)]
pub struct EncodedCredentials {
    username: String,
    password: String,
}

impl EncodedCredentials {
    /// Internal constructor used by [`Credentials::percent_encoded`].
    pub(crate) fn new(username: String, password: String) -> Self {
        Self { username, password }
    }

    /// Returns the percent-encoded username.
    #[must_use]
    pub fn username(&self) -> &str {
        &self.username
    }

    /// Returns the percent-encoded password. Treat as a secret —
    /// do not log, do not embed in error messages without
    /// redaction.
    #[must_use]
    pub fn password(&self) -> &str {
        &self.password
    }
}

/// Redacting `Debug` so a stray `dbg!(encoded)` cannot leak the
/// percent-encoded password onto stderr.
impl std::fmt::Debug for EncodedCredentials {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EncodedCredentials")
            .field("username", &self.username)
            .field("password", &"***")
            .finish()
    }
}

/// Drops eagerly clear the strings so the underlying buffer is
/// released as soon as the value goes out of scope, rather than
/// waiting for the parent struct to fall out of scope. **Does
/// not zero the heap bytes** — true zeroing requires the
/// `zeroize` crate (the project forbids `unsafe`, so we cannot
/// reach the underlying byte buffer in stdlib safe Rust). Adding
/// `zeroize` is deferred to a future LTSC patch — see the v0.2
/// roadmap.
impl Drop for EncodedCredentials {
    fn drop(&mut self) {
        self.password.clear();
        self.username.clear();
    }
}

/// Reasons a credential pair failed validation.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Error)]
#[non_exhaustive]
pub enum InvalidCredentials {
    /// The trimmed username was empty.
    #[error("username must not be empty")]
    EmptyUsername,
    /// The trimmed password was empty.
    #[error("password must not be empty")]
    EmptyPassword,
    /// **Domain-F#2 (v0.1.7.17):** username contained a non-
    /// `alphaDash` character (matches the Laravel panel's rule).
    /// The contained `char` is the first offending character so
    /// the UI can show "username can't contain '@'", not just
    /// "invalid".
    #[error("username may only contain letters, digits, '-', or '_'")]
    IllegalUsernameChar(char),
    /// **Hardening (v2.0.18-pre):** username exceeded the
    /// 64-char Laravel cap. Reported with both `max` and `got`
    /// so the UI can render "username too long (got 80, max 64)".
    #[error("username too long (got {got}, max {max})")]
    UsernameTooLong {
        /// Configured cap.
        max: usize,
        /// Length that overflowed it.
        got: usize,
    },
    /// **Hardening (v2.0.18-pre):** password exceeded the 255-
    /// char cap matching Laravel's stored-cleartext column.
    #[error("password too long (got {got}, max {max})")]
    PasswordTooLong {
        /// Configured cap.
        max: usize,
        /// Length that overflowed it.
        got: usize,
    },
}

/// Laravel's `alphaDash` rule: ASCII letters, digits, dash, underscore.
/// Centralised here so the validation tests + the parser share one
/// definition (anyone changing the rule must update both sides).
const fn is_alpha_dash(c: char) -> bool {
    matches!(
        c,
        'A'..='Z' | 'a'..='z' | '0'..='9' | '-' | '_'
    )
}

/// Percent-encodes a string against the URL userinfo character set used by
/// Swift (`CharacterSet.urlUserAllowed` minus `:@/?#[]`).
fn percent_encode_userinfo(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for byte in input.bytes() {
        if is_unreserved_or_subdelim(byte) {
            out.push(char::from(byte));
        } else {
            // Writing to a String is infallible, so the result is always Ok.
            let _ = write!(out, "%{byte:02X}");
        }
    }
    out
}

const fn is_unreserved_or_subdelim(byte: u8) -> bool {
    matches!(
        byte,
        b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9'
        | b'-' | b'.' | b'_' | b'~'
        | b'!' | b'$' | b'&' | b'\'' | b'(' | b')'
        | b'*' | b'+' | b',' | b';' | b'='
    )
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn rejects_empty_username() {
        assert_eq!(
            Username::parse("   "),
            Err(InvalidCredentials::EmptyUsername)
        );
    }

    #[test]
    fn rejects_empty_password() {
        assert_eq!(Password::parse(""), Err(InvalidCredentials::EmptyPassword));
    }

    /// **Hardening (v2.0.18-pre):** mirrors Laravel's
    /// `alphaDash` rule — `@`, `:`, `.`, space, and any other
    /// non-`[A-Za-z0-9_-]` char are rejected at parse time.
    #[test]
    fn rejects_non_alphadash_username() {
        assert!(matches!(
            Username::parse("alice@bad"),
            Err(InvalidCredentials::IllegalUsernameChar('@'))
        ));
        assert!(matches!(
            Username::parse("alice:bad"),
            Err(InvalidCredentials::IllegalUsernameChar(':'))
        ));
        assert!(matches!(
            Username::parse("alice bad"),
            Err(InvalidCredentials::IllegalUsernameChar(' '))
        ));
        assert!(matches!(
            Username::parse("alice.bad"),
            Err(InvalidCredentials::IllegalUsernameChar('.'))
        ));
    }

    /// `_` and `-` are part of `alphaDash`, so they must pass.
    /// (Regression guard: the regex-style implementation could
    /// accidentally exclude them when narrowed.)
    #[test]
    fn accepts_alphadash_username() {
        assert!(Username::parse("alice_bob").is_ok());
        assert!(Username::parse("alice-bob").is_ok());
        assert!(Username::parse("Alice123").is_ok());
    }

    /// Mirrors Laravel `maxLength(64)`. 65 chars must fail with
    /// `UsernameTooLong`, 64 must succeed.
    #[test]
    fn enforces_username_max_length() {
        let ok = "a".repeat(USERNAME_MAX_LEN);
        assert!(Username::parse(&ok).is_ok());
        let too_long = "a".repeat(USERNAME_MAX_LEN + 1);
        assert!(matches!(
            Username::parse(&too_long),
            Err(InvalidCredentials::UsernameTooLong {
                max: USERNAME_MAX_LEN,
                got
            }) if got == USERNAME_MAX_LEN + 1
        ));
    }

    /// Password length cap matches the server-side cleartext column.
    #[test]
    fn enforces_password_max_length() {
        let ok = "p".repeat(PASSWORD_MAX_LEN);
        assert!(Password::parse(&ok).is_ok());
        let too_long = "p".repeat(PASSWORD_MAX_LEN + 1);
        assert!(matches!(
            Password::parse(&too_long),
            Err(InvalidCredentials::PasswordTooLong {
                max: PASSWORD_MAX_LEN,
                got
            }) if got == PASSWORD_MAX_LEN + 1
        ));
    }

    #[test]
    fn password_debug_redacts() {
        let p = Password::parse("hunter2").unwrap();
        assert_eq!(format!("{p:?}"), "Password(\"***\")");
    }

    /// `Username::Debug` must redact the plaintext exactly like
    /// `Password`. The original implementation forwarded `&self.0` to
    /// `debug_tuple` which leaked the username on every panic /
    /// tracing dump that captured a `Credentials` struct.
    #[test]
    fn username_debug_redacts() {
        let u = Username::parse("alice").unwrap();
        assert_eq!(format!("{u:?}"), "Username(\"***\")");
    }

    /// `Username::Display` must redact too — the `{}` formatter would
    /// otherwise put the plaintext into any log line the caller forgot
    /// to special-case.
    #[test]
    fn username_display_redacts() {
        let u = Username::parse("alice").unwrap();
        assert_eq!(format!("{u}"), "***");
    }

    /// Round-trip the full `Credentials` struct through `{:?}` to
    /// guarantee neither field leaks even when both appear together.
    #[test]
    fn credentials_debug_redacts_both_fields() {
        let c = Credentials::new(
            Username::parse("alice").unwrap(),
            Password::parse("hunter2").unwrap(),
        );
        let dump = format!("{c:?}");
        assert!(!dump.contains("alice"), "username leaked via Debug: {dump}");
        assert!(
            !dump.contains("hunter2"),
            "password leaked via Debug: {dump}"
        );
    }

    #[test]
    fn password_expose_secret_returns_plaintext() {
        let p = Password::parse("hunter2").unwrap();
        assert_eq!(p.expose_secret(), "hunter2");
    }

    #[test]
    fn percent_encoding_preserves_unreserved() {
        assert_eq!(percent_encode_userinfo("alice"), "alice");
        assert_eq!(percent_encode_userinfo("a-b.c_d~e"), "a-b.c_d~e");
        assert_eq!(percent_encode_userinfo("0123456789"), "0123456789");
    }

    #[test]
    fn percent_encoding_escapes_reserved() {
        assert_eq!(percent_encode_userinfo("a:b"), "a%3Ab");
        assert_eq!(percent_encode_userinfo("a@b"), "a%40b");
        assert_eq!(percent_encode_userinfo("a/b"), "a%2Fb");
        assert_eq!(percent_encode_userinfo("a?b"), "a%3Fb");
        assert_eq!(percent_encode_userinfo("a#b"), "a%23b");
        assert_eq!(percent_encode_userinfo("a[b]"), "a%5Bb%5D");
    }

    #[test]
    fn percent_encoding_handles_non_ascii_utf8() {
        // "é" is U+00E9, encoded as bytes C3 A9.
        assert_eq!(percent_encode_userinfo("é"), "%C3%A9");
    }

    #[test]
    fn credentials_percent_encoded_pair() {
        let creds = Credentials::new(
            Username::parse("alice").unwrap(),
            Password::parse("p@ss/word").unwrap(),
        );
        let encoded = creds.percent_encoded();
        assert_eq!(encoded.username(), "alice");
        assert_eq!(encoded.password(), "p%40ss%2Fword");
    }

    /// `Debug` must redact the password (the username is not
    /// considered sensitive — same posture as `Credentials::Debug`).
    #[test]
    fn encoded_credentials_debug_redacts_password() {
        let creds = Credentials::new(
            Username::parse("alice").unwrap(),
            Password::parse("hunter2").unwrap(),
        );
        let encoded = creds.percent_encoded();
        let dbg = format!("{encoded:?}");
        assert!(!dbg.contains("hunter2"), "password leaked: {dbg}");
        assert!(dbg.contains("***"), "redaction marker missing: {dbg}");
    }
}
